### ISSUE TITLE
Extra-comma in scss handlebars templates ?

### ISSUE THREAD

**Issue by juliandescottes** [twolfson/spritesheet-templates#39]
Hi,

In scss.templates.handlebars, I think there are extra commas at lines 34 and 42 : 
- https://github.com/twolfson/spritesheet-templates/blob/master/lib/templates/scss.template.handlebars#L34
- https://github.com/twolfson/spritesheet-templates/blob/master/lib/templates/scss.template.handlebars#L42

The {{each}} helper used at line 41 also generates an extra comma. 

Found the issue while trying to build a project that uses grunt-spritesmith. For this project, the extra commas are breaking the build, but I checked the history of scss.templates.handlebars and the extra-commas have always been there.

If you confirm this is a mistake, I can submit a PR to change this.

Thanks !

**Comment by twolfson** [comment]
This is intentional change and should be backwards compatible. Previously, we were leveraging lists but doing it implicitly by not using the list syntax. This now covers that makes it apparent.

Can you elaborate on what is breaking? This has been tested against Ruby SASS and `libsass`.

https://github.com/twolfson/spritesheet-templates/blob/9.4.0/test/scss_test.js

**Comment by juliandescottes** [comment]
The issue occurs when SASS tries to compile from sass/scss to CSS.

The line that breaks the compilation is 

     $mysprite: (0px, 0px, 0px, 0px, 14px, 10px, 42px, 20px, '../images/sprites.png', 'mysprite', );

The error message from sass is : 

    Warning: Syntax error: Invalid CSS after "...g', 'mysprite', ": expected expression (e.g. 1px, bold), was ");"
            on line 24 of app/styles/includes/_sprites.scss
            from line 5 of app/styles/includes/_master.sass
            from line 13 of app/styles/main.sass
      Use --trace for backtrace.

I will try to isolate the issue in a sample I can share with you.

**Comment by twolfson** [comment]
Can you post your version of SASS as well?

```bash
sass --version
```

**Comment by juliandescottes** [comment]
Good point. This project is using Sass 3.2.10. 

I will try with a newer version.

**Comment by juliandescottes** [comment]
Just tested with 3.4.13 and it works fine !

Thanks for the support, sorry for wasting your time :/ 
You can close the issue.

**Comment by twolfson** [comment]
Ah, alright. Yea, 3.2.10 seems realtively old (July 2013). Going to consider this a wontfix for now. Thanks for the bug report, it was still good to consider =)

http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#3210_26_july_2013
