### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mixtur** [twolfson/spritesheet-templates#45]
Found typo. Either [there](https://github.com/twolfson/spritesheet-templates/blob/master/lib/spritesheet-templates.js#L340) or in documentation.

jsonArray_retina should probably be json_array_retina

**Comment by twolfson** [comment]
Ah, nice catch. I agree that we should probably stick with `snake_case` for the scheme instead of combining them. Since nobody has complained yet, then they prob aren't using it and we can prob move it to `json_array`/`json_array_retina`.

**Comment by twolfson** [comment]
We should double check our other documentation though before doing so (e.g. `spritesmith`/`grunt-spritesmith`/`gulp.spritesmith`)

**Comment by twolfson** [comment]
This has been resolved in `10.1.2` with correcting the templates to use `json_array`. Thanks for the bug report =)
