### ISSUE TITLE
SASS/SCSS template: change /* comments to //

### ISSUE THREAD

**Issue by dpolivy** [twolfson/spritesheet-templates#48]
With SASS partials, a `/* */` comment block ends up carrying through to the generated CSS, whereas inline comments (`// comment`) do not. The SASS/SCSS templates use comment blocks, and that ends up generating a bunch of extra, out of place, comments at the top of the generated CSS. It'd be a nice enhancement to update all of the associated templates to use inline comments instead.

**Comment by dpolivy** [comment]
BTW, I see this has been brought up a few times before (https://github.com/twolfson/spritesheet-templates/pull/34).  Is there a reason you're against just changing the block comments in the SASS templates to inline? It seems like it would fix this issue for everyone who cares, and not have any downside to those who don't.

**Comment by twolfson** [comment]
Multiline comment should be removed when the SASS compression mode `compressed` is used (only loud comments -- i.e. `/*!` or `//!` will be preserved)

http://stackoverflow.com/a/16846106

My hesitations to switching to `//` for multiline comments are:

- Adds tedium of prepending every line with `//` instead of `/* */` at head/tail
- Adds to visual clutter when reading through comment and copy/pasting for code reuse
- It shouldn't be a problem if used with appropriate compression and minification for production

**Comment by dpolivy** [comment]
But that assumes that one is using the `compressed` mode, which many (myself included) are not (and is _not_ the default). In development, I like to keep my generated code readable but clean, and using `compressed` would make that significantly more difficult. Plus, having big blobs of unrelated comments at the top of the CSS doesn't help. We do, of course, go through another concat and minification step before going into production, so this just affects my development flow, but it's irritating. I think it's pretty standard practice for SASS partials to use inline comments if it doesn't make sense for them to flow through to the output (i.e. if they are comments on mixins or variables; if it is a comment on a CSS style then the context would be preserved when it is compiled and that makes sense).

I've got a PR I can submit which fixes this and should remove any tedium from your end. It works quite well, actually, and I don't find it any more cluttered than before when reading the generated files, though I guess that is subjective. Since I'm not the only one to bring this up I urge you to reconsider what is a pretty rational request.

**Comment by twolfson** [comment]
I understand your frustration but I'm not convinced this is worth the trouble =/ The last request for this feature was 2 years ago. In development nowadays, I would expect people to view the sourcemap interpreted CSS rather than viewing the compiled CSS

I did some searching across SASS repos and found examples of both `//` and `/*` conventions:

https://github.com/inuitcss/inuitcss/blob/6.0.0-beta.4/generic/_generic.reset.scss#L1-L7

https://github.com/thoughtbot/bourbon/blob/v4.2.7/app/assets/stylesheets/functions/_contains.scss#L3-L16 (oddly a `///` pattern)

**Comment by dpolivy** [comment]
Actually, I think your examples exactly prove my point:

- In the first example, a block comment is used, as it is directly above a *CSS statement*. In this case, _both the comment and the CSS statement_ are output to the generated CSS file, so the comment is not "out of context" in the generated result.

- In the second example, the comment is on a `function` (but this applies to mixins, variables, etc -- any pre-processor goo that is compiled away by SASS). This is an inline comment, and does _not_ propagate to the end CSS, which is appropriate because the function it is commenting does not end up in the output, either.

Do you see the difference here?

I already went through and made the necessary changes (including tests), so there's not a lot of work if you did want to incorporate this. I haven't submitted a PR, but the commit is here: https://github.com/dpolivy/spritesheet-templates/commit/03471ecb86da5bd264bc2d7ad87e76e258f0bb49

**Comment by twolfson** [comment]
After some digging around the repo more, I see your point. Here's a SASS function in the same repo that's using `//` comments with a multiline comment:

https://github.com/inuitcss/inuitcss/blob/6.0.0-beta.4/tools/_tools.font-size.scss#L1-L14

Feel free to open up the PR. Also, do you happen to know if there's a canonical source documenting this convention (e.g. a major framework, SASS website)?

**Comment by dpolivy** [comment]
Thanks for reconsidering! I'm not sure of any canonical documentation for this, but here are a few links discussing it (mostly in the context of how to solve the problem rather than stating a specific preference):

https://sass-guidelin.es/#commenting

http://stackoverflow.com/questions/38070226/how-to-ignore-comments-in-sass-partial-files

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments

**Comment by twolfson** [comment]
Great, thanks for the links! I'll look over them when I get some free time =)

**Comment by twolfson** [comment]
Found another one: a prominent author (Harry Roberts) linked from the Sass guidelines:

http://cssguidelin.es/#preprocessor-comments

Also it turns out that `///` syntax is for Sassdoc (TIL):

http://sassdoc.com/annotations/#example

**Comment by twolfson** [comment]
This has been resolved by @dpolivy in #49 and released in `10.2.0`. Thanks again for taking the time to explain/convince me of the convention =)
