### ISSUE TITLE
sass ${{strings.name}} value

### ISSUE THREAD

**Issue by GuillaumeKadolis** [twolfson/spritesheet-templates#51]
into sass.template.handlebars this var should use previous var

`${{strings.name}}: ({{px.x}}, {{px.y}}, {{px.offset_x}}, {{px.offset_y}}, {{px.width}}, {{px.height}}, {{px.total_width}}, {{px.total_height}}, '{{{escaped_image}}}', '{{name}}', )`

should be

`${{strings.name}}: (${{strings.name_x}}, ${{strings.name_y}}, ${{strings.name_offset_x}}, ${{strings.name_offset_y}}, ${{strings.name_width}}, ${{strings.name_height}}, ${{strings.name_total_width}}, ${{strings.name_total_height}}, '${{strings.name_image}}', '${{strings.name_name}}:', )`

same issue with ${{spritesheet_info.strings.name}}:

${{strings.name_image}} hasn't the same value on each loop ?

**Comment by twolfson** [comment]
`strings` is for variable names themselves (e.g. `home-x`, `home-image`) whereas the values we use in the template are for the actual value (e.g. `x=22px`, `image=spritesheet.png`)
