### ISSUE TITLE
Security vulnerability - Denial of Service on Handlebar version less than 4.4.5

### ISSUE THREAD

**Issue by ekelvin** [twolfson/spritesheet-templates#56]
Can you please update handlebars to 4.4.5 where the security vulnerability of:
Denial of Service is pactched? 
[https://www.npmjs.com/advisories/1300](https://www.npmjs.com/advisories/1300)

**Comment by ekelvin** [comment]
pull request https://github.com/twolfson/spritesheet-templates/pull/57

**Comment by twolfson** [comment]
This has been resolved by #57 and released in `10.4.1`
