### ISSUE TITLE
Not all formatOpts making it into template

### ISSUE THREAD

**Issue by reintroducing** [twolfson/spritesheet-templates#59]
Hello, I'm using this with spritesmith and so far everything is working as expected, except one of my formatOpts that I'm passing is not making it into the template.  I'm using as such:
```
templater(
    {...regular, ...retina},
    {format, formatOpts: {type, relPath}}
)
```
The `type` is available in the handlebars template but `relPath` does not seem to be.

Source template with `type` set to `common` and `relPath` set to `../img/sprites`:
```
$sprite-{{options.type}}: (
    {{#items}}
    {{name}}: (
        offset-x: {{px.offset_x}},
        offset-y: {{px.offset_y}},
        width: {{px.width}},
        height: {{px.height}},
        total-width: {{px.total_width}},
        total-height: {{px.total_height}},
        image: "{{options.relPath}}/{{escaped_image}}"
    ),
    {{/items}}
);
```

Example output:
```
$sprite-common: (
    apple-pay: (
        offset-x: 0px,
        offset-y: -20px,
        width: 40px,
        height: 17px,
        total-width: 117px,
        total-height: 81px,
        image: "/sprite-common.png"
    ),
```

Expected output:
```
$sprite-common: (
    apple-pay: (
        offset-x: 0px,
        offset-y: -20px,
        width: 40px,
        height: 17px,
        total-width: 117px,
        total-height: 81px,
        image: "../img/sprites/sprite-common.png"
    ),
```

As you can see, the `image` path is incorrect. Am I misunderstanding the `formatOpts` or is this just a bug? If I'm misunderstanding, what is the best way to get this `relPath` into my template?

**Comment by reintroducing** [comment]
Aaaaanddd disregard. I realized {{options.relPath}} is not available in the loop. I rewrote this and solved my issue. Final output for anyone that may run into this (and also this isn't an issue with this, just my general lack of knowledge around handlebars):
```
$sprite-{{options.type}}: (
    {{#each items}}
    {{name}}: (
        offset-x: {{px.offset_x}},
        offset-y: {{px.offset_y}},
        width: {{px.width}},
        height: {{px.height}},
        total-width: {{px.total_width}},
        total-height: {{px.total_height}},
        image: "{{@root.options.relPath}}/{{escaped_image}}"
    ),
    {{/each}}
);
```

**Comment by twolfson** [comment]
Sadly, one of the confusing but also surprisingly good consistent attributes of Handlebars. Glad you figured it out =)

**Comment by reintroducing** [comment]
@twolfson apologies for the noise, i should have looked over the handlebars docs before assuming it was an issue with spritesheet-templates.
