### ISSUE TITLE
Please allow minor version updates for 'underscore' dependency

### ISSUE THREAD

**Issue by ttc229** [twolfson/spritesheet-templates#60]
Our project flagged a Security Vulnerability in the underscore dependency https://github.com/jashkenas/underscore/issues/2915 which is hoisted via spritesheet-templates.

The current package.json uses "underscore": "~1.4.2". The fix for the underscore vulnerability is in versions 1.12.1,1.13.0-2.

The semantic versioning allows us to upgrade patch versions but for this particular fix, we will need a minor version upgrade to get to 1.13.1

Is it possible to change this dependency to "underscore": "^1.4.2" to allow minor version upgrades as well?

**Comment by twolfson** [comment]
I prefer to stick to `~` because some libraries have introduced breaking changes in minor upgrades =/

That being said, I'll gladly accept a PR to bump vulnerable dependencies at any time =)

**Comment by ttc229** [comment]
Added Pull Request https://github.com/twolfson/spritesheet-templates/pull/61

**Comment by twolfson** [comment]
This has been patched and released via #61 in `10.5.1`
