### ISSUE TITLE
node_modules.bak in the published package for 10.5.1

### ISSUE THREAD

**Issue by VlasovSergey** [twolfson/spritesheet-templates#62]
When I run `npm i spritesheet-templates@10.5.1` the package is installed with the folder `node_modules.bak` inside.
Also, when I tried to download the package by link: https://registry.npmjs.org/spritesheet-templates/-/spritesheet-templates-10.5.1.tgz
This folder was there as well. 
Is that an expected behavior?

**Comment by twolfson** [comment]
Oh wow, good catch. Will fix that

**Comment by twolfson** [comment]
This has been patched in `10.5.2`

**Comment by fasergeyte** [comment]
Thanks for the very fast fix!
