### ISSUE TITLE
Less template error - "error evaluating function `%`: result.replace is not a function"

### ISSUE THREAD

**Issue by ncksllvn** [twolfson/spritesheet-templates#63]
I was upgrading some modules when I ran into the error below, which points to an issue with [this line](https://github.com/twolfson/spritesheet-templates/blob/10.5.2/lib/templates/less.template.handlebars#L93). I've tried multiple Less versions ranging from years old to latest, still getting this error. 

I'm sure I'm doing something wrong, but this error was not present on an [older version](https://github.com/twolfson/spritesheet-templates/blob/10.1.4/lib/templates/less.template.handlebars#L93). If I edit the template directly in `node_modules`, this error goes away.

```
[less] error evaluating function `%`: result.replace is not a function

22 |      bottom: 2px;
23 |      right: 5px;
24 |      .sprite(@radio-add);
   |      ^
25 |    }
26 |    .plus-green {

```
The value of `@radio-add` is `453px 211px -453px -211px 16px 16px 469px 408px '/generated/sprites/general.png' 'radioAdd';`, which is the `@sprite` param in the function below. 

```
.sprite-image(@sprite) {
  {{! DEV: We slice to trim off excess quotes on an escaped URL }}
  @sprite-image: extract(@sprite, 9);
  background-image: e(%('url(%a)', e(@sprite-image)));
}
```

Any idea what could be going on?

**Comment by twolfson** [comment]
Hmm, I'm not too sure. When I try to compile the generated file in our tests, it all works as expected

```bash
# I've appended a `.sprites(@spritesheet-sprites);` to the end of `less.less` here
./node_modules/.bin/lessc test/expected_files/less.less

# ...
.sprites(@spritesheet-sprites);
*/
.sprite-dash-case {
  background-image: url(nested/dir/spritesheet.png);
  background-position: 0px 0px;
  width: 10px;
  height: 20px;
}
.sprite_snake_case {
  background-image: url(nested/dir/spritesheet.png);
  background-position: -10px -20px;
  width: 20px;
  height: 30px;
}
.spriteCamelCase {
  background-image: url(nested/dir/spritesheet.png);
  background-position: -30px -50px;
  width: 50px;
  height: 50px;
}
```

This works both against the previously set up version (3.9.0) as well as the latest (4.1.3)

```bash
$ npm install less@latest --save-dev
$ ./node_modules/.bin/lessc --version
lessc 4.1.3 (Less Compiler) [JavaScript]
$ ./node_modules/.bin/lessc test/expected_files/less.less
# Same result as above
```

The functions still are documented in LESS so they should work, https://lesscss.org/functions/#string-functions

Are there any modifications being done to the `spritesmith` or LESS setup? Can you try copy/pasting the `test/expected_files/less.less` with some `.sprite()` or `.sprites()` invocations as a sanity check?

**Comment by ncksllvn** [comment]
@twolfson I appreciate you taking the time out of your day to assist me with this!

This is bizarre, but I have narrowed it down...My main Less file is just a collection of imports.  If I replace the contents of `"generated/sprites/general.less"` with that of `test/expected_files/less.less` then add some invocations to `.sprite`, I _do_ get the same error.

```less
@import "colors.less";
// ...
@import "generated/sprites/general.less";

.testing {
  .sprite(@sprite-snake-case);
}

// [vite] Internal server error: [less] error evaluating function `%`: result.replace is not a function
//  Plugin: vite:css
//  File: /Projects/vmobile-admin/app/less/main.less:52:2
//  50 |  
//  51 |  .testing {
//  52 |    .sprite(@sprite-snake-case);
//     |    ^
//  53 |  }
```

However, if I move it to the root, then I do not get the error.

```less
@import "colors.less";
// ...
@import "general.less"; // moved to root, everything works okay
```

These seems like just an importing issue at first but the twist is that I can leave `general.less` in `"generated/sprites` if I use the old version of the `.sprite-image` function inside `"generated/sprites/general.less"`.

```
// generated/sprites/general.less
// ...

.sprite-image(@sprite) {
  @sprite-image: extract(@sprite, 9);
  @sprite-image-bare: ~`"@{sprite-image}".slice(1, -1)`;
  background-image: url(@sprite-image-bare);
}

// ...
```

Obviously I have some options for workarounds here, but still this is very strange!

**Comment by ncksllvn** [comment]
It seems to be something with the `url` function bc when replaced with `URL` this doesn't produce a compilation error.

```
.sprite-image(@sprite) {
  @sprite-image: extract(@sprite, 9);
  background-image: e(%('URL(%a)', e(@sprite-image)));
}

```

Could it be some sort of collision between the Less url function and the native CSS one? Though I don't understand why it would run okay either way from the root directory.

**Comment by ncksllvn** [comment]
To fully reproduce for me -

```less
// main.less
@import "subdir/less.less"

.testing {
  .sprite(@sprite-snake-case);
}
```

```less
// subdir/less.less
// -> contents of https://raw.githubusercontent.com/twolfson/spritesheet-templates/master/test/expected_files/less.less
```

**Comment by ncksllvn** [comment]
As it turns out, I seem to be able to compile `main.less` successfully directly using `lessc`, so it would seem that the error I'm running into is being triggered by something during the overall build process. I'm using a [vite plugin](https://github.com/evont/vite-plugin-spritesmith), maybe something there.

So sorry about this and thanks again for your time.

**Comment by ncksllvn** [comment]
I haven't debugged deeper yet, but I think this is the line where the error occurs, https://github.com/vitejs/vite/blob/5a56941a895fd0ffdbdbf0094336fb7f0f4099c1/packages/vite/src/node/plugins/html.ts#L815. 

Edit - seems to be related to this - https://github.com/vitejs/vite/issues/13143

**Comment by twolfson** [comment]
Oh wow! That seems like really promising progress!!

Going to mark this issue as "closed" since it sounds like the issue is around Vite and its configuration, since `lessc` works fine

If it helps, I'd recommend taking a binary search approach to tracking down the issue. i.e.

1. Try a vanilla Vite build with no custom configs and get it working (good reference)
2. Reintroduce full config where we know it doesn't work (bad reference)
3. Binary search by commenting out half the lines/half the build
4. Continue by enabling/disabling lines until you find it works

(this assumes that Vite is a somewhat similar config to other build tools, but generally binary search troubleshooting is the fastest for me)

**Comment by ncksllvn** [comment]
Great advice, thanks again for your help @twolfson !
